import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import './form.css'
import { ToastProvider } from "../components/toast/ToastContext";
import ClientLayout from "./ClientLayout";

export const metadata: Metadata = {
  title: "Blocq Finance",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ClientLayout>
          <ToastProvider>
            {children}
          </ToastProvider>
        </ClientLayout>
      </body>
    </html>
  );
}
